/**
 * Render an array of Endpoints into a single TypeScript source string.
 *
 * Output shape: a `makeEndpoints(http)` factory that returns the entire
 * API tree (typed), plus a ZooData class that wires HttpClient through it.
 */
import type { Endpoint } from "./extract";
import type { CliPath } from "./classifier";

interface NamedEndpoint extends Endpoint {
  identifier: string;
}

/**
 * Tree node. A node can be:
 *   - a pure leaf:     { endpoint: NamedEndpoint }
 *   - a pure branch:   { children: { [key]: TreeNode } }
 *   - both:            { endpoint, children }   (rendered as Object.assign)
 */
interface TreeNode {
  endpoint?: NamedEndpoint;
  children?: Record<string, TreeNode>;
}

const HEADER = `// AUTO-GENERATED by scripts/codegen.ts — DO NOT EDIT BY HAND.
//
// This file is regenerated whenever openapi/openapi.v2.json changes.
// Edits here will be lost on the next codegen run.

import type { paths } from "./types";
import { HttpClient, type ClientOptions } from "../client";

`;

export function render(endpoints: Endpoint[]): string {
  const named = endpoints.map((ep) => ({ ...ep, identifier: identifierFor(ep) }));

  const wrappers = named.map(renderWrapper).join("\n");
  const tree = buildTree(named);
  const treeLiteral = renderBranch(tree, 2);

  return `${HEADER}export function makeEndpoints(http: HttpClient) {
${wrappers}
  return ${treeLiteral};
}

export type ZooDataApi = ReturnType<typeof makeEndpoints>;

export interface ZooData extends ZooDataApi {}
export class ZooData {
  constructor(opts: ClientOptions) {
    Object.assign(this, makeEndpoints(new HttpClient(opts)));
  }
}
`;
}

function renderWrapper(ep: NamedEndpoint): string {
  const pathKey = JSON.stringify(ep.path);
  const responseType = `paths[${pathKey}]["${ep.method}"]["responses"][200]["content"]["application/json"]`;

  if (ep.method === "post" && ep.hasRequestBody) {
    const requestType = `paths[${pathKey}]["${ep.method}"]["requestBody"]["content"]["application/json"]`;
    return `  const ${ep.identifier} = (body: ${requestType}): Promise<${responseType}> =>
    http.request({ method: "POST", path: ${pathKey}, body });`;
  }
  if (ep.method === "get" && ep.hasPathParams) {
    const interpolated = interpolatePath(ep.path);
    return `  const ${ep.identifier} = (jobId: string): Promise<${responseType}> =>
    http.request({ method: "GET", path: \`${interpolated}\` });`;
  }
  return `  const ${ep.identifier} = (): Promise<${responseType}> =>
    http.request({ method: "${ep.method.toUpperCase()}", path: ${pathKey} });`;
}

function interpolatePath(path: string): string {
  // v1 only emits one path-param endpoint (jobId).
  return path.replace(/\{\w+\}/g, "${encodeURIComponent(jobId)}");
}

function buildTree(endpoints: NamedEndpoint[]): TreeNode {
  const root: TreeNode = { children: {} };
  for (const ep of endpoints) {
    placeAt(root, ep.primary, ep);
    for (const alias of ep.aliases) placeAt(root, alias, ep);
  }
  return root;
}

function placeAt(root: TreeNode, position: CliPath, ep: NamedEndpoint): void {
  let cur: TreeNode = root;
  for (let i = 0; i < position.length - 1; i++) {
    const key = position[i]!;
    cur.children ??= {};
    cur.children[key] ??= {};
    cur = cur.children[key];
  }
  const leafKey = position[position.length - 1]!;
  cur.children ??= {};
  const existing = cur.children[leafKey];
  if (existing) {
    if (existing.endpoint && existing.endpoint.identifier !== ep.identifier) {
      throw new Error(
        `codegen: collision at ${position.join("/")}: ${existing.endpoint.identifier} vs ${ep.identifier}`,
      );
    }
    existing.endpoint = ep;
  } else {
    cur.children[leafKey] = { endpoint: ep };
  }
}

function renderBranch(node: TreeNode, indent: number): string {
  const pad = " ".repeat(indent);
  const childIndent = indent + 2;
  const childPad = " ".repeat(childIndent);

  const entries: string[] = [];
  for (const [key, child] of Object.entries(node.children ?? {})) {
    entries.push(`${childPad}${formatKey(key)}: ${renderNode(child, childIndent)}`);
  }
  return `{\n${entries.join(",\n")}\n${pad}}`;
}

function renderNode(node: TreeNode, indent: number): string {
  const hasLeaf = Boolean(node.endpoint);
  const hasChildren = node.children && Object.keys(node.children).length > 0;
  if (hasLeaf && !hasChildren) return node.endpoint!.identifier;
  if (!hasLeaf && hasChildren) return renderBranch(node, indent);
  // hasLeaf && hasChildren — e.g., crawl + crawl.status
  const branch = renderBranch(node, indent);
  return `Object.assign(${node.endpoint!.identifier}, ${branch})`;
}

function formatKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

/**
 * Derive a stable JS identifier from an endpoint's CLI path.
 * Joins kebab-case + path segments as camelCase: e.g.
 *   ["ecommerce", "amazon", "products", "search"]      -> ecommerceAmazonProductsSearch
 *   ["webtools", "scrape-interactive"]                 -> webtoolsScrapeInteractive
 */
function identifierFor(ep: Endpoint): string {
  const tokens = ep.primary.flatMap((seg) => seg.split("-"));
  return tokens
    .map((tok, i) => (i === 0 ? tok : tok[0]!.toUpperCase() + tok.slice(1)))
    .join("");
}
